# Generated by Django 3.1.3 on 2020-11-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.category')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('comments', models.TextField(blank=True, max_length=1000, verbose_name='Commentaires')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.category')),
                ('color', models.ManyToManyField(to='knowledge.Color')),
            ],
        ),
    ]
