# Generated by Django 3.1.3 on 2020-11-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_auto_20201130_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetal',
            name='wiki',
            field=models.URLField(blank=True, max_length=150, verbose_name='Wikipedia'),
        ),
    ]
