# Generated by Django 3.1.3 on 2020-12-02 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0003_vegetal_wiki'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Couleur', 'verbose_name_plural': 'Couleurs'},
        ),
        migrations.AlterModelOptions(
            name='vegetal',
            options={'ordering': ['name'], 'verbose_name': 'Plante', 'verbose_name_plural': 'Plantes'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.category', verbose_name='Catégorie parente'),
        ),
        migrations.AlterField(
            model_name='vegetal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='vegetal',
            name='color',
            field=models.ManyToManyField(to='knowledge.Color', verbose_name='Couleurs dominantes'),
        ),
        migrations.AlterField(
            model_name='vegetal',
            name='wiki',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Wikipedia'),
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_answers', models.IntegerField(default=0, verbose_name='Bonnes réponses')),
                ('bad_answers', models.IntegerField(default=0, verbose_name='Mauvaises réponses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
