# Generated by Django 3.1.3 on 2020-12-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_auto_20201202_0638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
